### PR TITLE
Updated for Swift 3

### PR DESCRIPTION
**Pull request by quentinlesceller**
Just a simple update for Swift 3.

### CODE REVIEW

**Comment by ldiqual** [comment]
@quentinlesceller Awesome! Thanks for contributing. Are those changes backward compatible with swift 2? (I'm thinking about the `UnsafeMutablePointer` init) If not, can you wrap the breaking changes with `#if swift(>=3.0)`? Reference: https://github.com/apple/swift-evolution/blob/master/proposals/0020-if-swift-version.md

**Comment by quentinlesceller** [comment]
Actually, function like `++` and the rest are deprecated and will be removed in Swift 3. So I guess there is no backward compatibility. I will wrap the breaking changes.

**Comment by ldiqual** [comment]
@quentinlesceller the `++ => += 1` changes are backward compatible, they'll work with swift 2. I was more concerned about the UnsafeMutablePointer init, not sure it's available in swift 2.

**Comment by quentinlesceller** [comment]
Yes sorry I just understand what you meant. I'm using Swift 2.2 and all of this changes are working if that's what you are asking for.

**Comment by ldiqual** [comment]
Awesome. Can you add a line in CHANGELOG.md saying something like "Fixed swift 3 compiler warnings"? Will merge after that.

**Comment by quentinlesceller** [comment]
Yep no problem. I had it under "unreleased master".

**Comment by ldiqual** [comment]
Merged in https://github.com/TakeScoop/SwiftyRSA/commit/16462d57cac4780db487c2a81011d59b067b559d

@quentinlesceller Thanks a lot for contributing to SwiftyRSA! I’ve invited you to join the SwiftyRSA maintainers group – no pressure to accept! Feel free to get back to me if you have any question, and thanks again!

**Pull request closed without merging**
