### PR TITLE
Support Swift Package Manager

### PR DESCRIPTION
**Pull request by bednarj4**
Very simple support for SPM, just a new library product for SwiftyRSA.
There are ways to cheese Obj-C code into a package, but migrating the single Objective-C class seemed more straightforward. 
Tested with Xcode 11.7 and 12.0.1

### CODE REVIEW

**Review by murilxaraujo — APPROVED** [review]

**Comment by shuguenot** [comment]
Hello, i have this error on app startup :

```
dyld: Library not loaded: @rpath/SwiftyRSA.framework/SwiftyRSA
  Referenced from: /private/var/containers/Bundle/Application/2787A571-AF63-4955-A48B-CAA0D60C5216/App.app/App
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

**Comment by bednarj4** [comment]
Hello @shuguenot , is SwiftyRSA added as a dependency to the app directly or a dependency of the app?

**Comment by shuguenot** [comment]
> Hello @shuguenot , is SwiftyRSA added as a dependency to the app directly or a dependency of the app?

Directly added as a dependency

Package.resolved
   ```
   {
        "package": "SwiftyRSA",
        "repositoryURL": "https://github.com/bednarj4/SwiftyRSA",
        "state": {
          "branch": "master",
          "revision": "c18eb3c617bc087eb4d48bf910ae704e865ac5c8",
          "version": null
        }
      },

```

**Comment by bednarj4** [comment]
Please check if in the Xcode's target settings > General tab > Frameworks, Libraries and Embedded Content SwiftyRSA is marked as `Embed & Sign`. 
Because for my own purposes I had to make the library dynamic it has to be explicitly marked as delivered with the application.

**Comment by shuguenot** [comment]
Thanks @bednarj4 it's working 👍

**Review by lexon — APPROVED** [review]

**Comment by lexon** [comment]
Any updates here? Would like to switch to SPM using official repo.

**Review by distivi — APPROVED** [review]

**Comment by lexon** [comment]
any updates?

**Review by Gabanelli — APPROVED** [review]

**Review by shuguenot — APPROVED** [review]

**Review by Adobels — APPROVED** [review]

**Review by Adobels — APPROVED** [review]

**Review by Romza — APPROVED** [review]

**Review by DevNathan — APPROVED** [review]

**Comment by FitzAfful** [comment]
Is there an update on this? It doesn't seem possible to add SwiftyRSA using SPM. Currently getting the error: 

`has no package.swift manifest in https://github.com/TakeScoop/SwiftyRSA`

**Comment by renevdkooi** [comment]
> Is there an update on this? It doesn't seem possible to add SwiftyRSA using SPM. Currently getting the error:
> 
> `has no package.swift manifest in https://github.com/TakeScoop/SwiftyRSA`

You can actually add this, but requires a bit of an extra step.
1. Add the package as you normaly would and enter URL https://github.com/bednarj4/SwiftyRSA
2. It will auto switch to the original URL (TakeScoop) and complain, it will ask you "Add Anyway?"
3. Pres add anyway, which will cause it to add, but not download
4. Go into your project file, show content, drill down and find the file inside xcodeproj>xworkspace->xsshareddata>swiftpm->Package resolved.
5. Add the rules @shuguenot shuguenot wrote
6. Close your project and re-open
7. Go to frameworks and search for SwiftyRSA and add it, set to EMBED & SIGN

Now you can compile and include it. If you don't embed and sign, you will get a crash.

**Comment by FitzAfful** [comment]
Your structured solution worked for me. Thanks @renevdkooi 🙏🏾

**Comment by bangnguyengrab** [comment]
Hi, @bednarj4 can you resolve the conflict, and we can merge this, more and more people needs SPM support

**Comment by bigbangvn** [comment]
Hi @bednarj4 could you resolve the conflict then we can get approve and merge.

**Comment by glennposadas** [comment]
Hi @bednarj4 Have you had the chance to review the conflicts? Thanks!

**Comment by reshadf** [comment]
Any chance this is still on the radar somewhere to be fixed??

**Review by glennposadas — APPROVED** [review]

**Comment by eudoxius** [comment]
@glennposadas please see the new PR when you get a chance - thanks!

**Comment by pc-scoop** [comment]
merged from https://github.com/TakeScoop/SwiftyRSA/pull/231

**Pull request closed without merging**
