### PR TITLE
Support Swift Package Manager (Merge conflicts resolved)

### PR DESCRIPTION
**Pull request by ThrownToys**
This is a duplicate of bednarj4's work with merge conflicts resolved. [See the original PR #197 here]( https://github.com/TakeScoop/SwiftyRSA/pull/197)

### CODE REVIEW

**Review by Carrione — APPROVED** [review]

**Comment by bryanlee-hdj** [comment]
Hello! Is there any one to merge this awesome PR?
I need the savior ;)

**Review by songtao046 — APPROVED** [review]

**Comment by songtao046** [comment]
Is there anyone who can merge this PR?

**Comment by songtao046** [comment]
Could you please help merge this pr? Need the SPM
@ldiqual @quentinlesceller @paulw11 @nickm01 @pmacro @greenantdotcom @nickneiman  @hyerra

**Comment by reshadf** [comment]
would love to see this merged

**Review by nickneiman — APPROVED** [review]

**Comment by basememara** [comment]
@nickm01 @ikeith needs one more approval for SPM support, can you help?

**Review by bryanlee-hdj — APPROVED** [review]

**Review by escakot — APPROVED** [review]

**Review by pc-scoop — APPROVED** [review]

**Pull request merged**
