### PR TITLE
Swift 3.0 changes

### PR DESCRIPTION
**Pull request by ldiqual**
@paulw11 @quentinlesceller Please review

### Checklist

 - [ ] Make tests pass on Xcode 8 beta
 - [ ] Change circle.yml to support Xcode 8 beta (not available yet)

### Description

This fixes all the swift 3.0 errors for SwiftyRSA. It required adding a Data+SHA.swift bridge for our ObjC SHAx helpers.

### Tests

Important note: none of the tests pass because of an iOS 10 or Xcode 8 bug:

```
...
Test Case '-[SwiftyRSAObjcTests testDataEncryptDecrypt]' started.
2016-07-08 00:38:24.079048 xctest[77869:1841902] [OSStatus] error:[-34018] Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
```

Related post on the Apple Dev forum: https://forums.developer.apple.com/thread/51071

### Additional details

After we merge this into `swift-3.0`, I'd like to start making the API feel more "swifty" by renaming most of the methods. A couple examples:

```
- encryptData(data)
- encryptString(string)
+ encrypt(data: data)
+ encrypt(string: string)

- verifySignatureData(data)
+ verifySignature(data: data)

etc.
```

What do you think?

### CODE REVIEW

**Comment by paulw11** [comment]
Since Swift 3 is going to break lots of stuff for lots of people anyway (<rant>Seriously Apple, Swift 3 is going to cost a lot of people a lot of time deleting two letter prefixes and so on</rant>) it is probably a good time to change the function signatures.

**Comment by ldiqual** [comment]
As of now, SwiftyRSA breaks with Xcode 8 GM while running tests in the simulator. It returns `secStatus = -34018`.

**Comment by ldiqual** [comment]
Found a workaround for iOS 10 and xcode 8. Tests pass on both iOS 9 and 10 in the simulator. Will wait on travis to merge.

**Comment by ldiqual** [comment]
Tested extensively in one of my production apps and automated tests pass locally. Merging now, will fix travis after.

**Pull request merged**
