### PR TITLE
Support for Xcode 10 & Swift 4.2

### PR DESCRIPTION
**Pull request by rhysforyou**
This PR takes the steps necessary to get the project building without warnings in Xcode 10 and Swift 4.2. Specifically:

- Updates the project's Swift version to 4.2 in build settings
- Updates SwiftLint to the latest version for Swift 4.2 compatibility
- Fixes all of the new warnings that SwiftLint version introduced
- Updates the project's Podspec to target Swift 4.2
- Updates the Swift version badge in the project's README

### CODE REVIEW

**Comment by rynecheow** [comment]
When would this be merged?

**Comment by freak4pc** [comment]
This looks good. Any thoughts on when you'll have time for this? @ldiqual

**Comment by ldiqual** [comment]
@rhysforyou Thanks a lot for this! I'll be allocating time this week to go over this + the circleci migration. Is this Swift 4.1 / Xcode 9 compatible?

**Comment by rhysforyou** [comment]
I'd moved the Swift target up to 4.2, but I just now rolled it back to 4.1 and it builds in both Xcode 9.4 and Xcode 10 without issue.

**Comment by ldiqual** [comment]
Merged as part of 1e4ff8d3b2a78f2439910ad17594fbe008727e0a which also includes project/target reorganization because of commandline build failures. Releasing now

**Comment by ldiqual** [comment]
@rhysforyou Thanks a ton for doing this btw, you rock!

**Comment by rhysforyou** [comment]
Awesome! Thanks for getting a release out so quick!

**Pull request closed without merging**
